server:
    port: 18081

dubbo:
    protocol:
        # dubbo 协议
        name: dubbo
        # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
        port: -1
    registry:
        # 挂载到 Spring Cloud 注册中心
        address: spring-cloud://localhost
    cloud:
        subscribed-services: sca-provider
    consumer:
        check: false

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/seata-test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
        username: root
        password: 123456

    cloud:
        nacos:
            # Nacos 服务注册发现
            discovery:
                server-addr: 127.0.0.1:8848
                username: nacos
                password: nacos
                namespace: yclimb
        alibaba:
            seata:
                # Seata 事务组名称，对应file.conf文件中 vgroup_mapping.my_test_tx_group
                tx-service-group: my_test_tx_group

mybatis:
    mapper-locations: classpath:mapper/*.xml



